# Generated by Django 6.0.7 on 2026-09-01 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='nom complet')),
                ('service', models.CharField(default='Direction des services académiques', max_length=120, verbose_name='service')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'agent',
                'verbose_name_plural': 'agents',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='référence')),
                ('requerant', models.CharField(max_length=120, verbose_name='requérant')),
                ('province', models.CharField(max_length=60, verbose_name='province')),
                ('diplome', models.CharField(max_length=160, verbose_name='diplôme')),
                ('pays', models.CharField(max_length=80, verbose_name='pays d’obtention')),
                ('etat', models.CharField(choices=[('a_instruire', 'À instruire'), ('pieces_manquantes', 'Pièces manquantes'), ('verification', 'Vérification externe'), ('commission', 'Avis de la commission'), ('signature', 'En signature'), ('decidee', 'Décidée')], default='a_instruire', max_length=20, verbose_name='état')),
                ('deposee_le', models.DateField(verbose_name='déposée le')),
                ('montant_usd', models.DecimalField(decimal_places=2, default=85, max_digits=8, verbose_name='frais (USD)')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('instructeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equivalences.agent', verbose_name='instructeur')),
            ],
            options={
                'verbose_name': 'demande d’équivalence',
                'verbose_name_plural': 'demandes d’équivalence',
                'ordering': ['deposee_le'],
            },
        ),
    ]
